services:
  app:
    build: ./service
    container_name: python-microservice-starter-app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: python-microservice-starter-redis
    ports:
      - "6379:6379"

  nginx:
    image: nginx:alpine
    container_name: python-microservice-starter-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
